### ISSUE TITLE
NativeMessagingHosts registry key hives

### ISSUE THREAD

**Issue by DavidBE-UK** [aclap-dev/vdhcoapp#89] opened 2021-02-09 17:44 UTC
I note that the coapp installer creates NativeMessagingHosts keys in the HKLM hive, rather than in the HKEY_CURRENT_USER hive like the other extensions that use NativeMessaging I have do. This has the effect that in Edge, VDH doesn't work in the Dev and Canary channel builds, with the coapp 'not found' as the nativemessaging connection isn't allowed. Simply adding the coapp NativeMessagingHosts key in the HKCU hive alongside the ones from other extensions has the coapp now showing as present in Edge Dev and Canary and working like the other extensions that create their NativeMessagingHosts there on install. Should you reconsider which hive the coapp installer creates registry keys in? For one thing, it means you'd get bug reports from Dev users which would give you a heads-up about upcoming problems from browser changes with time to fix them before those changes hit the standard channel.

**Comment by paulrouget** [comment] 2023-09-06 06:19
@DavidBE-UK at the monent, we use HKLM indeed, but it doesn't seem to impact Edge Dev & Canary (just tested).

I'm gonna close this as this seems to work as intended. Feel free to re-open if necessary.

**Closed by paulrouget** 2023-09-06 06:19 UTC
